name       : kaddressbook
version    : 18.08.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kaddressbook-18.08.0.tar.xz : 0c0b6be1c3f44d4938a3c7dc76579d0ec7904382a7ce6dc9ca1ea73da3c5f8f1
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : office
summary    : KDE Contact Manager
description: |
    KAddressBook stores all the personal details of your family, friends and other contacts..
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - pimcommon-devel
    - prison-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
