name       : kaddressbook
version    : 20.12.2
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kaddressbook-20.12.2.tar.xz : 1e4498135a2fe0a332d87a4c15e24522db2c9216a00a8f23c17887addca11a77
homepage   : https://kde.org/applications/office/org.kde.kaddressbook
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE Contact Manager
description: |
    KAddressBook stores all the personal details of your family, friends and other contacts..
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kimap-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - libkleo-devel
    - gpgme-qt-devel
    - pimcommon-devel
    - prison-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
