name       : kaddressbook
version    : 18.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kaddressbook-18.12.0.tar.xz : f2568b8a5ae47502af82583fe49d934655f751165289026308d528ae8de5d535
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE Contact Manager
description: |
    KAddressBook stores all the personal details of your family, friends and other contacts..
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - pimcommon-devel
    - prison-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
