name       : kaddressbook
version    : 22.08.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kaddressbook-22.08.3.tar.xz : 8373c20df9125cc392b524916f236da6b5e6641b6dc5d3640dd4f878a5580d87
homepage   : https://kde.org/applications/office/org.kde.kaddressbook
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE Contact Manager
description: |
    KAddressBook stores all the personal details of your family, friends and other contacts..
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kimap-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - libkleo-devel
    - gpgme-qt-devel
    - pimcommon-devel
    - prison-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
