name       : kaddressbook
version    : 19.08.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kaddressbook-19.08.2.tar.xz : 4d67480ebf8ee96fcde85e66f8ad32119b006e36c87f4e4ac20ecfa967599260
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE Contact Manager
description: |
    KAddressBook stores all the personal details of your family, friends and other contacts..
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - pimcommon-devel
    - prison-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
